global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Сам Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Метрики системы
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Метрики Docker контейнеров
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
